version: "3.9"
services:
  zookeeper:
    image: zookeeper:3.9.1
    container_name: "zookeeper"
    ports:
      - "2181:2181"
    volumes:
      - type: volume
        source: notificator-zookeeper-data
        target: /var/lib/zookeeper/data
      - type: volume
        source: notificator-zookeeper-logs
        target: /var/lib/zookeeper/logs
  kafka:
    image: bitnami/kafka:3.6.0
    container_name: "kafka"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${DOCKER_HOST_IP:-127.0.0.1}:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - type: volume
        source: notificator-kafka
        target: /var/lib/kafka/data
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8090:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092,kafka2:29093
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    links:
      - kafka
      - zookeeper

volumes:
  notificator-zookeeper-data:
  notificator-zookeeper-logs:
  notificator-kafka: